### ISSUE TITLE
Astral Sorcery Console Errors

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/New-MMD-Public-Pack#44]
[04:12:07] [Netty Epoll Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel Astral Sorcery
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:112) ~[FMLOutboundHandler$OutboundTarget$3.class:?]
        at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:297) ~[FMLOutboundHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:235) ~[SimpleNetworkWrapper.class:?]
        at hellfirepvp.astralsorcery.common.data.SyncDataHolder.tick(SyncDataHolder.java:124) ~[SyncDataHolder.class:?]
        at hellfirepvp.astralsorcery.common.auxiliary.tick.TickManager.serverTick(TickManager.java:63) ~[TickManager.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1370_TickManager_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by ProxyNeko** [comment]
Has this been sent to the mod author and explained a bit more?

**Comment by Ruchian** [comment]
I don't know if it's possible, but maybe you should assign @HellFirePvP or link this [here](https://github.com/HellFirePvP/AstralSorcery/issues) somehow. (I'm not too sure how to github properly myself xd)

**Comment by Morpheus1101** [comment]
https://github.com/HellFirePvP/AstralSorcery/issues/513 - No known cause, but added to being some of the other weirdness network stuff thats occured .. next update may fix, but due to no known cause to replicate, unknown to if it will be a fix at this stage.
