### ISSUE TITLE
[Bug] Draconic Staff of Power

### ISSUE THREAD

**Issue by Ruchian** [MinecraftModDevelopment/New-MMD-Public-Pack#53]
Hi,

I wanted to report this bug Holiness is experiencing.

After the recent server pack update, Holiness is unable to log in for some reason. Perhaps there are others who experience the same issue. At least, in case of Holiness, she gets the following crash error when attemping to connect to the public server:

```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.brandon3055.draconicevolution.items.tools.MiningToolBase.lambda$getFields$0(MiningToolBase.java:124)
	at com.brandon3055.draconicevolution.items.tools.MiningToolBase$$Lambda$3433/1455002715.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at com.brandon3055.draconicevolution.items.tools.MiningToolBase.getFields(MiningToolBase.java:123)
	at com.brandon3055.draconicevolution.items.tools.DraconicStaffOfPower.getFields(DraconicStaffOfPower.java:99)
	at com.brandon3055.draconicevolution.items.tools.ToolBase.addDisplayData(ToolBase.java:212)
	at com.brandon3055.draconicevolution.client.handler.HudHandler.clientTick(HudHandler.java:136)
	at com.brandon3055.draconicevolution.client.handler.ClientEventHandler.tickEnd(ClientEventHandler.java:93)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2090_ClientEventHandler_tickEnd_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

I don't think the whole report is nessecary. The problem is the equipped item "The draconic staff of power". Since the update, it's causing Holiness to crash. Even the stacktrace points out to this.

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.brandon3055.draconicevolution.items.tools.MiningToolBase.lambda$getFields$0(MiningToolBase.java:124)
	at com.brandon3055.draconicevolution.items.tools.MiningToolBase$$Lambda$3433/1455002715.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at com.brandon3055.draconicevolution.items.tools.MiningToolBase.getFields(MiningToolBase.java:123)
	at com.brandon3055.draconicevolution.items.tools.DraconicStaffOfPower.getFields(DraconicStaffOfPower.java:99)
	at com.brandon3055.draconicevolution.items.tools.ToolBase.addDisplayData(ToolBase.java:212)
	at com.brandon3055.draconicevolution.client.handler.HudHandler.clientTick(HudHandler.java:136)
	at com.brandon3055.draconicevolution.client.handler.ClientEventHandler.tickEnd(ClientEventHandler.java:93)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2090_ClientEventHandler_tickEnd_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
```

What I think happened is that, perhaps a block inside the item filter suddenly got removed due to the update, which causes the issue, but I myself have no honest clue.

If you really want a crash report about this, than maybe asking for one that is up to date is better. Anyway, this is the reason why Holiness isn't playing at least.

I was wondering if you could try removing and replacing the item with a similar one. (I believe holiness's staff has been upgraded, but I am not too certain about this either.) Even if you in the end give one without upgrades or just keep it with the removal of the item, I think this should help resolve the meantioned issue.

Thanks for reading and in advance for the support you give.

**Comment by Morpheus1101** [comment]
i've flicked brandon3055 a msg to take a look at this, but being the Easter weekend here it may not be for a day or 2

**Comment by Morpheus1101** [comment]
Can you upload the entire crash log to pastebin//gist and link here as well plz

**Comment by Morpheus1101** [comment]
Its so far been tracked to an enchantment, however brandon is still working on precise cause etc, will update more as further information comes to hand.

**Comment by Ruchian** [comment]
Ah! Now, that explains. I had the same tool, but what I didn't have was the Reaper Enchantment on it.
That is unexpected, I mean, it worked in pack version 0.0.9 without problems.

**Comment by Morpheus1101** [comment]
So, speaking a bit more with brandon, it does indeed seem like a prev enchantment was on the tool and since it no longer exists, is whats causing the issue, this is a bug thats going to take a lil bit to track down and fix, so as a temporary stop gap measure it should be fixed as we had to remove the tool

**Comment by Morpheus1101** [comment]
I spoke with brandon and it was also related to the java file and line number and what that code was referring to.  As for a tutorial on reading crash reports....umm, none that im aware of, a lot ive picked up myself over the yrs playing as well as starting to learn basics of coding itself and reading code and doing as you did in asking what/why/how they came to that conclusion.

**Comment by Morpheus1101** [comment]
This issue Should be fixed in the upcoming pack vers along with some others i discovered with DE

**Comment by ProxyNeko** [comment]
Have all of these issues been fixed now?

**Comment by Morpheus1101** [comment]
This issue has been fixed
